-- Apply in Supabase SQL editor before enabling operations suite.
create table if not exists public.gym_payments (
 id bigint generated by default as identity primary key,
 member_id bigint not null references public.members(id) on delete cascade,
 subscription_id bigint references public.subscriptions(id) on delete set null,
 amount numeric(12,2) not null check(amount > 0),
 note text,
 created_at timestamptz not null default now()
);
create index if not exists gym_payments_member_idx on public.gym_payments(member_id,created_at desc);
create table if not exists public.gym_attendance (
 id bigint generated by default as identity primary key,
 member_id bigint not null references public.members(id) on delete cascade,
 checked_in_at timestamptz not null default now()
);
create index if not exists gym_attendance_member_idx on public.gym_attendance(member_id,checked_in_at desc);
create table if not exists public.gym_activity_log (
 id bigint generated by default as identity primary key,
 member_id bigint references public.members(id) on delete set null,
 action text not null,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists gym_activity_log_time_idx on public.gym_activity_log(created_at desc);
create table if not exists public.gym_subscription_events (
 id bigint generated by default as identity primary key,
 member_id bigint not null references public.members(id) on delete cascade,
 subscription_id bigint references public.subscriptions(id) on delete set null,
 plan_id bigint,
 price numeric(12,2) not null default 0,
 start_date date,
 end_date date,
 created_at timestamptz not null default now()
);
create index if not exists gym_sub_events_member_idx on public.gym_subscription_events(member_id,created_at desc);
-- Restrict access to trusted server credentials; do not expose these tables to anonymous browser clients.
alter table public.gym_payments enable row level security;
alter table public.gym_attendance enable row level security;
alter table public.gym_activity_log enable row level security;
alter table public.gym_subscription_events enable row level security;
